api:
 build: .
 dockerfile: DockerfileVotingApi
 ports:
  - 5000:5000

admin:
 build: .
 dockerfile: DockerfileVotingAdmin
 ports:
  - 8080:5000
 links:
  - api

ui:
 build: ./voting-ui
 ports:
  - 80:3000
 links:
  - api
